import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LOGO_BASE64 } from './logo-base64';
import * as ExcelJS from 'exceljs';

export const exportToPDF = (
  title: string, 
  headers: string[][], 
  data: any[][], 
  filename: string, 
  metadata?: { period: string; dept: string; clerk: string },
  summary?: { label: string; value: string }[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // 1. Header Section
  // Add Logo in top left
  try {
    doc.addImage(LOGO_BASE64, 'PNG', 15, 10, 20, 20);
  } catch (e) {
    console.error("Failed to add logo to PDF", e);
  }

  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("PAKISTAN NAVY", pageWidth / 2, 22, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("CIVILIAN MANAGEMENT SYSTEM · RESTRICTED", pageWidth / 2, 30, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text(title || "Payment Bill", pageWidth / 2, 42, { align: 'center' });

  // Ref & Date
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/ /g, '-');
  doc.text(`Ref: PN/CIV/OVE/2026/04`, pageWidth - 15, 15, { align: 'right' });
  doc.text(`Date: ${today}`, pageWidth - 15, 20, { align: 'right' });

  doc.setLineWidth(0.5);
  doc.line(15, 48, pageWidth - 15, 48);

  // 2. Metadata Section
  let currentY = 58;
  if (metadata) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("PERIOD", 15, currentY);
    doc.text("DEPARTMENT", pageWidth / 2 - 20, currentY);
    doc.text("GENERATED BY", pageWidth - 15, currentY, { align: 'right' });

    doc.setFont("helvetica", "normal");
    doc.text(metadata.period, 15, currentY + 5);
    doc.text(metadata.dept, pageWidth / 2 - 20, currentY + 5);
    doc.text(metadata.clerk, pageWidth - 15, currentY + 5, { align: 'right' });
    currentY += 15;
  }

  // 3. Summary Section (Optional)
  if (summary && summary.length > 0) {
    const boxWidth = (pageWidth - 30) / summary.length;
    summary.forEach((item, index) => {
      const x = 15 + (index * boxWidth);
      doc.setDrawColor(200, 200, 200);
      doc.rect(x, currentY, boxWidth - 2, 15);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text(item.label.toUpperCase(), x + 2, currentY + 5);
      doc.setFontSize(10);
      doc.text(item.value, x + 2, currentY + 11);
    });
    currentY += 25;
  }

  // 4. Table Section
  autoTable(doc, {
    head: headers,
    body: data,
    startY: currentY,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 3, font: "helvetica" },
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 15, right: 15, bottom: 20 },
  });

  // 5. Signatures Section
  let finalY = (doc as any).lastAutoTable.finalY + 25;
  const pageHeight = doc.internal.pageSize.height;

  // Check if we need a new page for signatures
  if (finalY + 30 > pageHeight) {
    doc.addPage();
    finalY = 30;
  }

  const sigWidth = 45;
  const p1 = 15;
  const p2 = (pageWidth / 2) - (sigWidth / 2);
  const p3 = pageWidth - 15 - sigWidth;

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  
  // Prep By
  doc.line(p1, finalY, p1 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("PREPARED BY", p1 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("(System Generated)", p1 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Ver By
  doc.line(p2, finalY, p2 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("VERIFIED BY", p2 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("Admin Officer", p2 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Appr By
  doc.line(p3, finalY, p3 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("APPROVED BY", p3 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("Commanding Officer", p3 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(`Printed on: ${new Date().toLocaleString()} · Page 1 of 1`, pageWidth / 2, pageHeight - 10, { align: 'center' });

  doc.save(`${filename}.pdf`);
};

export const exportToExcel = async (sheetName: string, headers: string[], data: any[][], filename: string) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(sheetName);

  // Set Page Setup to A4 and Fit to Width
  worksheet.pageSetup = {
    paperSize: 9, // A4
    orientation: headers.length > 7 ? 'landscape' : 'portrait',
    fitToPage: true,
    fitToWidth: 1,
    fitToHeight: 0, // dynamic
    margins: {
      left: 0.5, right: 0.5,
      top: 0.5, bottom: 0.5,
      header: 0.3, footer: 0.3
    }
  };

  // 1. Add Branding
  // Logo
  try {
    const logoId = workbook.addImage({
      base64: LOGO_BASE64.split(',')[1],
      extension: 'png',
    });
    worksheet.addImage(logoId, {
      tl: { col: 0.2, row: 0.2 },
      ext: { width: 80, height: 80 }
    });
  } catch (e) {
    console.warn("Logo add failed for Excel", e);
  }

  // Titles
  const startCol = 3;
  const endCol = Math.max(headers.length, 6);
  
  const titleCell = worksheet.getCell(1, startCol);
  titleCell.value = 'PAKISTAN NAVY';
  titleCell.font = { name: 'Arial', size: 18, bold: true };
  worksheet.mergeCells(1, startCol, 1, endCol);
  titleCell.alignment = { horizontal: 'center' };

  const subTitleCell = worksheet.getCell(2, startCol);
  subTitleCell.value = 'CIVILIAN MANAGEMENT SYSTEM · RESTRICTED';
  subTitleCell.font = { name: 'Arial', size: 10, italic: true, color: { argb: 'FF666666' } };
  worksheet.mergeCells(2, startCol, 2, endCol);
  subTitleCell.alignment = { horizontal: 'center' };

  const reportTitleCell = worksheet.getCell(3, startCol);
  reportTitleCell.value = sheetName.toUpperCase();
  reportTitleCell.font = { name: 'Arial', size: 14, bold: true, color: { argb: 'FFD4AF37' } }; // Gold
  worksheet.mergeCells(3, startCol, 3, endCol);
  reportTitleCell.alignment = { horizontal: 'center' };

  // Date Printed
  const dateCell = worksheet.getCell(4, endCol);
  dateCell.value = `Generated on: ${new Date().toLocaleDateString()}`;
  dateCell.font = { name: 'Arial', size: 8, italic: true };
  dateCell.alignment = { horizontal: 'right' };

  // 2. Add Headers (Row 6)
  const headerRow = worksheet.addRow([]); // Spacer
  const actualHeaderRow = worksheet.getRow(6);
  headers.forEach((h, i) => {
    const cell = actualHeaderRow.getCell(i + 1);
    cell.value = h;
    cell.font = { name: 'Arial', size: 12, bold: true, color: { argb: 'FFFFFFFF' } };
    cell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' }
    };
    cell.alignment = { horizontal: 'center', vertical: 'middle' };
    cell.border = {
      top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' }
    };
  });
  actualHeaderRow.height = 25;

  // 3. Add Data (Starting at Row 7)
  data.forEach((row, rowIndex) => {
    const r = worksheet.addRow(row);
    r.eachCell((cell) => {
      cell.font = { name: 'Arial', size: 12 };
      cell.alignment = { vertical: 'middle' };
      cell.border = {
        top: { style: 'thin' }, left: { style: 'thin' }, bottom: { style: 'thin' }, right: { style: 'thin' }
      };
      // Alternate row colors
      if (rowIndex % 2 === 1) {
        cell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8FAFC' }
        };
      }
    });
  });

  // 4. Formulas (Total Row)
  const lastRowIndex = worksheet.lastRow ? worksheet.lastRow.number + 1 : 7;
  const totalRow = worksheet.getRow(lastRowIndex);
  totalRow.getCell(1).value = 'TOTALS / SUMMARY';
  totalRow.getCell(1).font = { name: 'Arial', size: 12, bold: true };
  
  // Try to sum numeric columns (heuristic: columns from index 2 onwards)
  headers.forEach((_, i) => {
    if (i > 0) {
      const colLetter = worksheet.getColumn(i + 1).letter;
      const startRow = 7;
      const endRow = lastRowIndex - 1;
      // We only apply formula if the column seems to contain numbers in the first data row
      const firstDataVal = worksheet.getRow(startRow).getCell(i + 1).value;
      if (typeof firstDataVal === 'number') {
        totalRow.getCell(i + 1).value = {
          formula: `SUM(${colLetter}${startRow}:${colLetter}${endRow})`,
          result: 0
        };
        totalRow.getCell(i + 1).font = { name: 'Arial', size: 12, bold: true };
      }
    }
  });

  // 5. Auto-width columns
  worksheet.columns.forEach(column => {
    let maxLen = 10;
    column.eachCell({ includeEmpty: true }, cell => {
      const val = cell.value ? cell.value.toString() : "";
      if (val.length > maxLen) maxLen = val.length;
    });
    column.width = maxLen + 5;
  });

  // Save File
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `${filename}.xlsx`;
  anchor.click();
  window.URL.revokeObjectURL(url);
};
