import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import ExcelJS from 'exceljs';

export const exportToPDF = (
  title: string, 
  headers: string[][], 
  data: any[][], 
  filename: string, 
  metadata?: { period: string; dept: string; clerk: string },
  summary?: { label: string; value: string }[]
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // 1. Header Section
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("PAKISTAN NAVY", pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text("CIVILIAN MANAGEMENT SYSTEM · RESTRICTED", pageWidth / 2, 27, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(title || "Payment Bill", pageWidth / 2, 35, { align: 'center' });

  // Ref & Date
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  const today = new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/ /g, '-');
  doc.text(`Ref: PN/CIV/OVE/2026/04`, pageWidth - 15, 15, { align: 'right' });
  doc.text(`Date: ${today}`, pageWidth - 15, 20, { align: 'right' });

  doc.setLineWidth(0.5);
  doc.line(15, 42, pageWidth - 15, 42);

  // 2. Metadata Section
  let currentY = 52;
  if (metadata) {
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.text("PERIOD", 15, currentY);
    doc.text("DEPARTMENT", pageWidth / 2 - 20, currentY);
    doc.text("GENERATED BY", pageWidth - 15, currentY, { align: 'right' });

    doc.setFont("helvetica", "normal");
    doc.text(metadata.period, 15, currentY + 5);
    doc.text(metadata.dept, pageWidth / 2 - 20, currentY + 5);
    doc.text(metadata.clerk, pageWidth - 15, currentY + 5, { align: 'right' });
    currentY += 15;
  }

  // 3. Summary Section (Optional)
  if (summary && summary.length > 0) {
    const boxWidth = (pageWidth - 30) / summary.length;
    summary.forEach((item, index) => {
      const x = 15 + (index * boxWidth);
      doc.setDrawColor(200, 200, 200);
      doc.rect(x, currentY, boxWidth - 2, 15);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text(item.label.toUpperCase(), x + 2, currentY + 5);
      doc.setFontSize(10);
      doc.text(item.value, x + 2, currentY + 11);
    });
    currentY += 25;
  }

  // 4. Table Section
  autoTable(doc, {
    head: headers,
    body: data,
    startY: currentY,
    theme: 'grid',
    styles: { fontSize: 8, cellPadding: 3, font: "helvetica" },
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    margin: { left: 15, right: 15, bottom: 20 },
  });

  // 5. Signatures Section
  let finalY = (doc as any).lastAutoTable.finalY + 25;
  const pageHeight = doc.internal.pageSize.height;

  // Check if we need a new page for signatures
  if (finalY + 30 > pageHeight) {
    doc.addPage();
    finalY = 30;
  }

  const sigWidth = 45;
  const p1 = 15;
  const p2 = (pageWidth / 2) - (sigWidth / 2);
  const p3 = pageWidth - 15 - sigWidth;

  doc.setDrawColor(0, 0, 0);
  doc.setLineWidth(0.5);
  
  // Prep By
  doc.line(p1, finalY, p1 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("PREPARED BY", p1 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("(System Generated)", p1 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Ver By
  doc.line(p2, finalY, p2 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("VERIFIED BY", p2 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("Admin Officer", p2 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Appr By
  doc.line(p3, finalY, p3 + sigWidth, finalY);
  doc.setFontSize(7); doc.setFont("helvetica", "bold");
  doc.text("APPROVED BY", p3 + sigWidth / 2, finalY + 5, { align: 'center' });
  doc.setFontSize(6); doc.setFont("helvetica", "normal");
  doc.text("Commanding Officer", p3 + sigWidth / 2, finalY + 8, { align: 'center' });

  // Footer
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(`Printed on: ${new Date().toLocaleString()} · Page 1 of 1`, pageWidth / 2, pageHeight - 10, { align: 'center' });

  doc.save(`${filename}.pdf`);
};

export const exportToExcel = async (sheetName: string, headers: string[], data: any[][], filename: string) => {
  const workbook = new ExcelJS.Workbook();
  const worksheet = workbook.addWorksheet(sheetName);
  worksheet.addRow(headers);
  data.forEach(row => worksheet.addRow(row));
  worksheet.getRow(1).font = { bold: true };
  const buffer = await workbook.xlsx.writeBuffer();
  const blob = new Blob([buffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
  const url = window.URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = `${filename}.xlsx`;
  anchor.click();
};
