import { AppShell, PageHeader } from '@/components/pncms/AppShell';
import { Btn, Section, Badge } from '@/components/pncms/ui-kit';
import { Printer, FileText, FileSpreadsheet, ArrowLeft } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import crest from '@/assets/navy-crest.png';
import { payments } from '@/data/mock';

const ReportPreview = () => {
  const navigate = useNavigate();
  const { slug } = useParams();
  const title = (slug ?? 'overtime-payment-bill')
    .replace(/-/g, ' ')
    .replace(/\b\w/g, (c) => c.toUpperCase());
  return (
    <AppShell>
      <PageHeader
        title="Report Preview"
        subtitle={`${title} · April 2026`}
        actions={
          <>
            <Btn variant="outline" onClick={() => navigate('/reports')}>
              <ArrowLeft className="w-4 h-4" /> Back
            </Btn>
            <Btn variant="outline">
              <Printer className="w-4 h-4" /> Print
            </Btn>
            <Btn variant="primary">
              <FileText className="w-4 h-4" /> PDF
            </Btn>
            <Btn variant="gold">
              <FileSpreadsheet className="w-4 h-4" /> Excel
            </Btn>
          </>
        }
      />

      <Section title="Document Preview">
        <div className="bg-white border border-border shadow-elevated mx-auto max-w-4xl p-12 font-body">
          <div className="flex items-center justify-between border-b-2 border-primary pb-5">
            <img src={crest} alt="crest" className="w-16 h-16 object-contain" />
            <div className="text-center flex-1">
              <h1 className="text-2xl text-primary">Pakistan Navy</h1>
              <p className="text-xs uppercase tracking-widest text-muted-foreground mt-1">
                Civilian Management System · Restricted
              </p>
              <p className="text-sm font-semibold mt-2">{title}</p>
            </div>
            <div className="text-[0.65rem] text-right text-muted-foreground">
              <div>
                Ref: PN/CIV/{(slug || 'RPT').toUpperCase().slice(0, 3)}/2026/04
              </div>
              <div className="mt-1">Date: 28-Apr-2026</div>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4 my-6 text-xs">
            <div>
              <div className="label-mil">Period</div>
              <div className="font-semibold">April 2026</div>
            </div>
            <div>
              <div className="label-mil">Department</div>
              <div className="font-semibold">All Departments</div>
            </div>
            <div>
              <div className="label-mil">Generated By</div>
              <div className="font-semibold">Admin Clerk · DIL-ADM-04</div>
            </div>
          </div>

          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="bg-primary text-white">
                <th className="border border-primary px-2 py-2 text-left">#</th>
                <th className="border border-primary px-2 py-2 text-left">
                  Employee
                </th>
                <th className="border border-primary px-2 py-2 text-left">
                  Cadre
                </th>
                <th className="border border-primary px-2 py-2 text-right">
                  Gross Hrs
                </th>
                <th className="border border-primary px-2 py-2 text-right">
                  Payable
                </th>
                <th className="border border-primary px-2 py-2 text-right">
                  Rate
                </th>
                <th className="border border-primary px-2 py-2 text-right">
                  Amount
                </th>
                <th className="border border-primary px-2 py-2 text-center">
                  Status
                </th>
              </tr>
            </thead>
            <tbody>
              {payments.map((p, i) => (
                <tr key={p.emp}>
                  <td className="border border-border px-2 py-1.5">{i + 1}</td>
                  <td className="border border-border px-2 py-1.5">{p.emp}</td>
                  <td className="border border-border px-2 py-1.5">
                    {p.cadre}
                  </td>
                  <td className="border border-border px-2 py-1.5 text-right font-mono">
                    {p.gross}
                  </td>
                  <td className="border border-border px-2 py-1.5 text-right font-mono">
                    {p.payable}
                  </td>
                  <td className="border border-border px-2 py-1.5 text-right font-mono">
                    {p.rate}
                  </td>
                  <td className="border border-border px-2 py-1.5 text-right font-mono font-semibold">
                    {p.amount.toLocaleString()}
                  </td>
                  <td className="border border-border px-2 py-1.5 text-center">
                    <Badge
                      variant={
                        p.status === 'Paid'
                          ? 'paid'
                          : p.status === 'Processed'
                            ? 'processed'
                            : 'pending'
                      }
                    >
                      {p.status}
                    </Badge>
                  </td>
                </tr>
              ))}
              <tr className="bg-muted font-bold">
                <td
                  colSpan={6}
                  className="border border-border px-2 py-2 text-right"
                >
                  GRAND TOTAL
                </td>
                <td className="border border-border px-2 py-2 text-right font-mono">
                  {payments.reduce((s, p) => s + p.amount, 0).toLocaleString()}
                </td>
                <td className="border border-border" />
              </tr>
            </tbody>
          </table>

          <div className="grid grid-cols-3 gap-12 mt-16 text-xs text-center">
            {[
              'Prepared By\nAdmin Clerk',
              'Verified By\nSection Officer',
              'Approved By\nDirector (Civilian)',
            ].map((s) => (
              <div
                key={s}
                className="border-t-2 border-primary pt-2 whitespace-pre-line font-semibold uppercase tracking-wider"
              >
                {s}
              </div>
            ))}
          </div>
        </div>
      </Section>
    </AppShell>
  );
};
export default ReportPreview;
